version: '3'
services:
  db:
    image: mariadb:10.4.11
    environment:
      - MYSQL_DATABASE=iv_tracker
      - MYSQL_USER=iv_user
      - MYSQL_PASSWORD=iv_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8180:8080"